* Importing Wikidata item normalized ranks to MySQL

** Requirements
   On Debian: python-mysql.connector

** How to import data
   Test data can be found [[https://analytics.wikimedia.org/datasets/one-off/article-recommender/20181130.tar.gz][here]].

   Assuming TSV files are in the current directory, run the following
   commands in order:

   1. Import languages (recommendationapi_password.txt must contain the MySQL
      password for the user 'recommendationapi'):

      python deploy.py import_languages 20181130 m2-master.eqiad.wmnet \
      3306 recommendationapi recommendationapi recommendationapi_password.txt \
      --language_file languages.tsv

   2. Import normalized ranks (make sure to change the source and target
      languages when importing other files):

      python deploy.py import_normalized_ranks 20181130 m2-master.eqiad.wmnet \
      3306 recommendationapi recommendationapi recommendationapi_password.txt \
      --normalized_ranks_file predictions-06032018-20181130/en-es.tsv \
      --source_language en --target_language es

   3. Create views so that the recommendation API can access the data:

      python deploy.py create_views 20181130 m2-master.eqiad.wmnet \
      3306 recommendationapi recommendationapi recommendationapi_password.txt

      (This doesn't always work. TODO: fix)

   4. Optional. If you want to delete old data:

      python deploy.py cleanup 20181130 m2-master.eqiad.wmnet \
      3306 recommendationapi recommendationapi recommendationapi_password.txt

** Prepare a deploy
   If any python dependencies have been updated the
   artifacts/ directory needs to be updated as well.
   On your local machine:

   - git rm artifacts/*.whl
   - ./bin/make-wheels.sh
   - ./bin/upload-wheels.py
   - git add artifacts/*.whl

   The make-wheels.sh script checks the current oozie task for a
   requirements.txt. If present all necessary wheel's are collected into
   artifacts/ and a requirements-frozen.txt containing exact versioning
   is emitted.

   The upload-wheels.py script will sync the wheels to archiva. If a wheel
   already exists in archiva for the same version but a different sha1
   your local version will be replaced. Wheel upload requires setting up
   maven with [[https://wikitech.wikimedia.org/wiki/Archiva#Deploy_to_Archiva][WMF's Archiva]] configuration.

** Prepare environment for Oozie
   - ./bin/create-environment.sh
   - Copy over the generated zip file to the `artifacts` folder of
     [[https://gerrit.wikimedia.org/r/#/admin/projects/analytics/refinery][analytics/refinery]].
